#
#  Copyright 2015 VMware, Inc.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#
---
- name: Install epel when needed
  package:
    name: epel-release
    state: present
    update_cache: yes
  when: ansible_os_family == 'RedHat' and ansible_distribution != 'Fedora'

- name: Assure pip is not installed via package manager
  package: name={{ item }} state=absent
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  with_items:
    - python-pip

- name: Assure required packages installed (not Photon)
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - ca-certificates
    - python-setuptools
  when: ansible_distribution != 'VMware Photon'

- name: Assure required packages installed (Photon)
  shell: "tdnf install -y {{ item }}"
  with_items:
    - ca-certificates
    - python-setuptools
  register: result
  changed_when: "'Nothing to do' not in result.stdout"
  when: ansible_distribution == 'VMware Photon'
  tags:
    - skip_ansible_lint


- name: Assure pip installed via easy_install.
  command: easy_install pip
  args:
    creates: /usr/bin/pip
  when: ansible_distribution != 'Debian' and ansible_distribution != 'Ubuntu'

- name: Assure pip installed via easy_install.
  command: easy_install pip
  args:
    creates: /usr/local/bin/pip
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Upgrade basic pip packages
  pip:
    name: "{{ item }}"
    state: latest
  with_items:
    - pip
    - virtualenv
  tags:
    - skip_ansible_lint
